---
- name: Update /etc/hosts from inventory
  hosts: Smartlis
  lineinfile:
    dest: /etc/hosts 
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: '{{groups.Smartlis}}'
