---
- name: Create slservers tower group
  tower_group:
    inventory: aviles
    name: Smartlis
    state: present
    tower_username: admin
    tower_password: "{{ tower_pass }}"
      
- name: Add sl servers to group
  shell: tower-cli host associate --host {{ item }} --group Smartlis -u admin -p "{{ tower_pass }}"
  loop: "{{ vmware_vms_cluster_deployment.hostname }}"
