---
- import_tasks: config_cluster.yml
  when: rabbitmq_create_cluster
- import_tasks: service.yml
- import_tasks: cluster.yml
  when: (rabbitmq_create_cluster == true) and ( ansible_fqdn != rabbitmq_cluster_master )
